const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bulmaSidebar: [
    {
      type: "category",
      label: "Belajar Bulma",
      items: [
        "intro",
        "PengenalanBulmaTerminologiKonsep",
        "FormLoginLayoutDasar",
        "NavigasiMenuVertikal",
        "GridResponsifKomponenUmum",
        "BreadcrumbFileUpload",
        "TabelDanDropdown",
        "TabelLanjutanDanForm",
        "NotifikasiDanCardComponent",
        "IntegrasiVanillaJavaScript",
      ],
    },
  ],
};

export default sidebars;
